# Generated by pykickstart v3.66
#version=DEVEL
# Firewall configuration
firewall --enabled --service=mdns
# Keyboard layouts
keyboard --vckeymap=ru --xlayouts='us','ru' --switch='grp:alt_shift_toggle','grp_led:scroll'
# System language
lang ru_RU.UTF-8
# Network information
network  --bootproto=dhcp --device=link --activate
# Shutdown after installation
shutdown
repo --name=fedora --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch
repo --name=lastup --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f$releasever&arch=$basearch
repo --name="rpmfusionfree" --baseurl=https://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
repo --name="rpmfusionfreeupdates" --baseurl=https://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
repo --name="rpmfusionnonfree" --baseurl=https://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$basearch/os/
repo --name="rpmfusionnonfreeupdates" --baseurl=https://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/$basearch/
repo --name="rpmfusionnvidiadriver" --baseurl=https://download1.rpmfusion.org/nonfree/fedora/nvidia-driver/$releasever/$basearch/
repo --name="rpmfusionsteam" --baseurl=https://download1.rpmfusion.org/nonfree/fedora/steam/$releasever/$basearch/
repo --name="tigro" --baseurl=https://download.copr.fedorainfracloud.org/results/tigro/fedora43/fedora-$releasever-$basearch/
repo --name="openh264" --baseurl=https://download.copr.fedorainfracloud.org/results/tigro/unpatent/fedora-$releasever-$basearch/
repo --name="chrome" --baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
repo --name="edge" --baseurl=https://packages.microsoft.com/yumrepos/edge/
repo --name="onlyoffice" --baseurl=https://download.onlyoffice.com/repo/centos/main/noarch/
# Root password
rootpw --iscrypted --lock locked
# SELinux configuration
selinux --enforcing
# System services
services --disabled="sshd" --enabled="NetworkManager,ModemManager"
# System timezone
timezone Europe/Moscow
# Use network installation
url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch"
# X Window System configuration information
xconfig  --startxonboot
# System bootloader configuration
bootloader --location=none
# Clear the Master Boot Record
zerombr
# Partition clearing information
clearpart --all
# Disk partitioning information
part / --fstype="ext4" --size=12120
#part / --size=8576

%post
# Enable livesys services
systemctl enable livesys.service
systemctl enable livesys-late.service

# enable tmpfs for /tmp
systemctl enable tmp.mount

# make it so that we don't do writing to the overlay for things which
# are just tmpdirs/caches
# note https://bugzilla.redhat.com/show_bug.cgi?id=1135475
cat >> /etc/fstab << EOF
vartmp   /var/tmp    tmpfs   defaults   0  0
EOF

# work around for poor key import UI in PackageKit
rm -f /var/lib/rpm/__db*
echo "Packages within this LiveCD"
rpm -qa --qf '%{size}\t%{name}-%{version}-%{release}.%{arch}\n' |sort -rn
# Note that running rpm recreates the rpm db files which aren't needed or wanted
rm -f /var/lib/rpm/__db*

# go ahead and pre-make the man -k cache (#455968)
/usr/bin/mandb

# make sure there aren't core files lying around
rm -f /core*

# remove random seed, the newly installed instance should make it's own
rm -f /var/lib/systemd/random-seed

# convince readahead not to collect
# FIXME: for systemd

echo 'File created by kickstart. See systemd-update-done.service(8).' \
    | tee /etc/.updated >/var/.updated

# Drop the rescue kernel and initramfs, we don't need them on the live media itself.
# See bug 1317709
rm -f /boot/*-rescue*

# Disable network service here, as doing it in the services line
# fails due to RHBZ #1369794
systemctl disable network

# Remove machine-id on pre generated images
rm -f /etc/machine-id
touch /etc/machine-id

%end

%post

# set livesys session type
sed -i 's/^livesys_session=.*/livesys_session="gnome"/' /etc/sysconfig/livesys

%end

%post
cat > /etc/yum.repos.d/copr:copr.fedorainfracloud.org:tigro:fedora43.repo << EOF
[copr:copr.fedorainfracloud.org:tigro:fedora43]
name=Copr repo for fedora43 owned by tigro
baseurl=https://download.copr.fedorainfracloud.org/results/tigro/fedora43/fedora-\$releasever-\$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/tigro/fedora43/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
EOF

cat > /etc/yum.repos.d/copr:copr.fedorainfracloud.org:tigro:unpatent.repo << EOF
[copr:copr.fedorainfracloud.org:tigro:unpatent]
name=Copr repo for unpatent owned by tigro
baseurl=https://download.copr.fedorainfracloud.org/results/tigro/unpatent/fedora-\$releasever-\$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/tigro/unpatent/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
EOF

cat > /usr/share/glib-2.0/schemas/org.gnome.shell.extensions.arcmenu.gschema.override << EOF
[org.gnome.shell.extensions.arcmenu]
custom-menu-button-icon-size=40.0
EOF

cat > /usr/share/glib-2.0/schemas/org.gnome.shell.gschema.override << EOF
[org.gnome.shell]
favorite-apps=['google-chrome.desktop', 'org.gnome.Evolution.desktop', 'org.gnome.Calendar.desktop', 'org.telegram.desktop.desktop', 'com.gexperts.Tilix.desktop',  'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.Connections.desktop', 'org.gnome.Weather.desktop', 'org.gnome.Boxes.desktop', 'onlyoffice-desktopeditors.desktop', 'org.gnome.Showtime.desktop', 'com.github.neithern.g4music.desktop']
enabled-extensions=['appindicatorsupport@rgcjonas.gmail.com', 'dash-to-dock@micxgx.gmail.com', 'ddterm@amezin.github.com', 'update-extension@purejava.org', 'no-overview@fthx', 'clipboard-history@alexsaveau.dev','background-logo@fedorahosted.org']
EOF

sed -i "s@favorite-apps.*@favorite-apps=['google-chrome.desktop', 'org.gnome.Evolution.desktop', 'org.gnome.Calendar.desktop', 'org.telegram.desktop.desktop', 'com.gexperts.Tilix.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.Connections.desktop', 'org.gnome.Weather.desktop', 'org.gnome.Boxes.desktop', 'onlyoffice-desktopeditors.desktop', 'org.gnome.Showtime.desktop', 'com.github.neithern.g4music.desktop', 'anaconda.desktop']@" /usr/libexec/livesys/sessions.d/livesys-gnome

#enabled-extensions=['appindicatorsupport@rgcjonas.gmail.com', 'dash-to-panel@jderose9.github.com', 'ding@rastersoft.com', 'arcmenu@arcmenu.com', 'no-overview@fthx', 'notification-banner-reloaded@marcinjakubowski.github.com', 'clipboard-history@alexsaveau.dev','background-logo@fedorahosted.org']


cat > /usr/share/glib-2.0/schemas/com.gexperts.Tilix.gschema.override << EOF
[com.gexperts.Tilix.Keybindings]
session-add-down='<Primary><Super>Down'
session-add-right='<Primary><Super>Right'
terminal-maximize='<Primary><Super>Up'
EOF

glib-compile-schemas /usr/share/glib-2.0/schemas/ ||:

# Old anaconda installer
rpm -e --nodeps anaconda-webui ||:

# Configure docs
mkdir -p /usr/share/doc/tigro-configs

cat > /usr/share/doc/tigro-configs/README << EOF
Load tilix config:

---
dconf load /com/gexperts/Tilix/ < /usr/share/doc/tigro-configs/tilix.conf
---
EOF

# autoconfigure user
cat > /etc/xdg/autostart/tigro-user-configure.desktop << EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=Tigro User Configure
Comment=Configure desktop like tilix and others
Exec=/usr/share/doc/tigro-configs/tigro-user-configure
X-GNOME-Autostart-enabled=true
X-KDE-autostart-after=panel
X-Desktop-File-Install-Version=0.28
EOF

cat > /usr/share/doc/tigro-configs/tigro-user-configure << EOF
#!/bin/sh

if [ -f \$HOME/.config/tigro-user-configure ]; then
    exit 0
fi

# Load tilix configuration
dconf load / < /usr/share/doc/tigro-configs/tilix.conf

# add lock
touch \$HOME/.config/tigro-user-configure
EOF

chmod +x /usr/share/doc/tigro-configs/tigro-user-configure

# tilix configure
cat > /usr/share/doc/tigro-configs/tilix.conf << EOF
[org/gnome/settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Alt>r'
command='tilix'
name='Tilix'

[com/gexperts/Tilix]
copy-on-select=false
enable-wide-handle=true
focus-follow-mouse=true
paste-advanced-default=false
prompt-on-close=true
quake-specific-monitor=0
sidebar-on-right=false
terminal-title-style='normal'
theme-variant='dark'
warn-vte-config-issue=false
window-state=132
window-style='normal'

[keybindings]
session-add-down='<Primary><Super>Down'
session-add-right='<Primary><Super>Right'
terminal-maximize='<Primary><Super>Up'
win-view-sidebar='<Primary>grave'

[profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d]
background-color='#2E2E34343636'
default-size-columns=90
font='Monaco 14'
foreground-color='#EEEEEEEEECEC'
login-shell=true
palette=['#2E2E34343636', '#CCCC00000000', '#4E4E9A9A0606', '#FFFFE5E55353', '#34346565A4A4', '#EDEDD4D40000', '#060698209A9A', '#D3D3D7D7CFCF', '#555557575353', '#EFEF29292929', '#EBEBFFFF5F5F', '#FFFFE5E55353', '#72729F9FCFCF', '#CCCC15158585', '#3434E2E2E2E2', '#EEEEEEEEECEC']
terminal-bell='none'
use-system-font=false
use-theme-colors=false
visible-name='По умолчанию'
EOF

# Download font
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
mkdir -p /usr/share/fonts/monaco
wget https://gist.github.com/rogerleite/b50866eb7f7b5950da01ae8927c5bd61/raw/862b6c9437f534d5899e4e68d60f9bf22f356312/mfont.ttf -O - > /usr/share/fonts/monaco/Monaco_Linux.ttf
fc-cache

# install onlyoffice repo files
wget https://download.onlyoffice.com/repo/centos/main/noarch/onlyoffice-repo.noarch.rpm -O - > /tmp/onlyoffice-repo.noarch.rpm
rpm -ihv /tmp/onlyoffice-repo.noarch.rpm
rm -f /tmp/onlyoffice-repo.noarch.rpm

# Set chromium as browser by default
sed -i 's@org.mozilla.firefox.desktop@google-chrome.desktop@g' \
	/usr/share/applications/gnome-mimeapps.list

# Update PS1 for bash prompt
sed '/export SYSTEMD_PAGER=/a\
\
# Modern colors from 1998 year\
export PS1="\[\e[1;33m\][\[\e[1;32m\]\u\[\e[1;95m\]@\[\e[1;31m\]\h \[\e[01;36m\]\W\[\e[1;33m\]]$ \[\e[m\]"' /etc/skel/.bashrc

# Sudo w/o password
cat > /etc/sudoers.d/99-nopasswd << EOF
%wheel ALL=(ALL) NOPASSWD: ALL
EOF

# DNF fastest mirror
cat >> /etc/dnf/dnf.conf << EOF
fastestmirror=True
max_parallel_downloads=10
EOF

# https://www.gosuslugi.ru/landing/tls
cat > /etc/pki/ca-trust/source/anchors/gost-a1.crt << EOF
-----BEGIN CERTIFICATE-----
MIIBXTCCAQigAwIBAgIMAt6twN4AjBl4PHrWMAwGCCqFAwcBAQ
MCBQAwGzEZMBcGA1UEAwwQVENJIEdPU1QgUk9PVCBBMTAeFw0y
MjAzMzAwOTMzMThaFw0zMjAzMzAwOTMzMThaMBsxGTAXBgNVBA
MMEFRDSSBHT1NUIFJPT1QgQTEwZjAfBggqhQMHAQEBATATBgcq
hQMCAiMBBggqhQMHAQECAgNDAARASiE+O1G5yX8JjIS0RmQ2Im
2FKd0RhbOtdjaoAivB3ywbHLGb6deQBRd/MwLP2IrfIZcVb4QP
5PSYolD/Iu+ExaMjMCEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEw
EB/wQFMAMBAf8wDAYIKoUDBwEBAwIFAANBAOi6Dn7pxa/SSbV6
PsfROEKzsBnX6GGggo9wOELuZKfDYdy88/92yr2Aali+fEje63
XqhHoZExE0CNLoncM3ARc=
-----END CERTIFICATE-----
EOF

cat > /etc/pki/ca-trust/source/anchors/ecdsa-a1.crt << EOF
-----BEGIN CERTIFICATE-----
MIIBVDCB+6ADAgECAgwB3q3A3gCMGXg8etYwCgYIKoZIzj0EAw
IwHDEaMBgGA1UEAwwRVENJIEVDRFNBIFJPT1QgQTEwHhcNMjIw
MzMwMDkzMzE4WhcNMzIwMzMwMDkzMzE4WjAcMRowGAYDVQQDDB
FUQ0kgRUNEU0EgUk9PVCBBMTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABJni7LJT4Gj86pG0s9wOefWgqgp/EGf4ZcSxNgAJfh
cl6WYNoWaZfflki4Rd0VzAJgbaTSW26zuv2mGM61txD96jIzAh
MA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MAoGCC
qGSM49BAMCA0gAMEUCIDKjKPoaZrqtljmuy60G1PYINvR3A1eL
OzT4RfhGBTrBAiEAhJL7IeLDbo2eZAIp4zioaIpo1hVyXkABNb
npOTQ9KPs=
-----END CERTIFICATE-----
EOF

cat > /etc/pki/ca-trust/source/anchors/rootca_ssl_rsa2022.cer << EOF
-----BEGIN CERTIFICATE-----
MIIFwjCCA6qgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwcDELMAkGA1UEBhMCUlUx
PzA9BgNVBAoMNlRoZSBNaW5pc3RyeSBvZiBEaWdpdGFsIERldmVsb3BtZW50IGFu
ZCBDb21tdW5pY2F0aW9uczEgMB4GA1UEAwwXUnVzc2lhbiBUcnVzdGVkIFJvb3Qg
Q0EwHhcNMjIwMzAxMjEwNDE1WhcNMzIwMjI3MjEwNDE1WjBwMQswCQYDVQQGEwJS
VTE/MD0GA1UECgw2VGhlIE1pbmlzdHJ5IG9mIERpZ2l0YWwgRGV2ZWxvcG1lbnQg
YW5kIENvbW11bmljYXRpb25zMSAwHgYDVQQDDBdSdXNzaWFuIFRydXN0ZWQgUm9v
dCBDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMfFOZ8pUAL3+r2n
qqE0Zp52selXsKGFYoG0GM5bwz1bSFtCt+AZQMhkWQheI3poZAToYJu69pHLKS6Q
XBiwBC1cvzYmUYKMYZC7jE5YhEU2bSL0mX7NaMxMDmH2/NwuOVRj8OImVa5s1F4U
zn4Kv3PFlDBjjSjXKVY9kmjUBsXQrIHeaqmUIsPIlNWUnimXS0I0abExqkbdrXbX
YwCOXhOO2pDUx3ckmJlCMUGacUTnylyQW2VsJIyIGA8V0xzdaeUXg0VZ6ZmNUr5Y
Ber/EAOLPb8NYpsAhJe2mXjMB/J9HNsoFMBFJ0lLOT/+dQvjbdRZoOT8eqJpWnVD
U+QL/qEZnz57N88OWM3rabJkRNdU/Z7x5SFIM9FrqtN8xewsiBWBI0K6XFuOBOTD
4V08o4TzJ8+Ccq5XlCUW2L48pZNCYuBDfBh7FxkB7qDgGDiaftEkZZfApRg2E+M9
G8wkNKTPLDc4wH0FDTijhgxR3Y4PiS1HL2Zhw7bD3CbslmEGgfnnZojNkJtcLeBH
BLa52/dSwNU4WWLubaYSiAmA9IUMX1/RpfpxOxd4Ykmhz97oFbUaDJFipIggx5sX
ePAlkTdWnv+RWBxlJwMQ25oEHmRguNYf4Zr/Rxr9cS93Y+mdXIZaBEE0KS2iLRqa
OiWBki9IMQU4phqPOBAaG7A+eP8PAgMBAAGjZjBkMB0GA1UdDgQWBBTh0YHlzlpf
BKrS6badZrHF+qwshzAfBgNVHSMEGDAWgBTh0YHlzlpfBKrS6badZrHF+qwshzAS
BgNVHRMBAf8ECDAGAQH/AgEEMA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsF
AAOCAgEAALIY1wkilt/urfEVM5vKzr6utOeDWCUczmWX/RX4ljpRdgF+5fAIS4vH
tmXkqpSCOVeWUrJV9QvZn6L227ZwuE15cWi8DCDal3Ue90WgAJJZMfTshN4OI8cq
W9E4EG9wglbEtMnObHlms8F3CHmrw3k6KmUkWGoa+/ENmcVl68u/cMRl1JbW2bM+
/3A+SAg2c6iPDlehczKx2oa95QW0SkPPWGuNA/CE8CpyANIhu9XFrj3RQ3EqeRcS
AQQod1RNuHpfETLU/A2gMmvn/w/sx7TB3W5BPs6rprOA37tutPq9u6FTZOcG1Oqj
C/B7yTqgI7rbyvox7DEXoX7rIiEqyNNUguTk/u3SZ4VXE2kmxdmSh3TQvybfbnXV
4JbCZVaqiZraqc7oZMnRoWrXRG3ztbnbes/9qhRGI7PqXqeKJBztxRTEVj8ONs1d
WN5szTwaPIvhkhO3CO5ErU2rVdUr89wKpNXbBODFKRtgxUT70YpmJ46VVaqdAhOZ
D9EUUn4YaeLaS8AjSF/h7UkjOibNc4qVDiPP+rkehFWM66PVnP1Msh93tc+taIfC
EYVMxjh8zNbFuoc7fzvvrFILLe7ifvEIUqSVIC/AzplM/Jxw7buXFeGP1qVCBEHq
391d/9RAfaZ12zkwFsl+IKwE/OZxW8AHa9i1p4GO0YSNuczzEm4=
-----END CERTIFICATE-----
EOF

update-ca-trust

%end

%packages
@^workstation-product-environment
@anaconda-tools
aajohan-comfortaa-fonts
anaconda-install-env-deps
anaconda-live
anaconda-gui
dracut-live
glibc-all-langpacks
gnome-initial-setup
kernel
kernel-modules
kernel-modules-extra
livesys-scripts
-@dial-up
-@input-methods
-@standard
-device-mapper-multipath
-fcoe-utils
#-gfs2-utils
-python3-botocore
-reiserfs-utils
-sdubby
# Tigro
-gnome-tour
-mediawriter
-pipewire-codec-aptx
NetworkManager-openconnect-gnome
celluloid
driver-manager
evolution
evolution-data-server
evolution-data-server-langpacks
evolution-ews
evolution-ews-langpacks
evolution-langpacks
f34-backgrounds-gnome
ffmpeg
ffmpeg-libs
fragments
g4music
gimp
gnome-boxes
gnome-calendar
gnome-shell-extension-dash-to-dock
gnome-shell-extension-dash-to-panel
gnome-shell-extension-ddterm
gnome-shell-extension-fedora-update
gnome-tweaks
gstreamer1-plugin-gtk4
gstreamer1-plugin-libav
gstreamer1-plugin-openh264
gstreamer1-plugins-bad-free
gstreamer1-plugins-bad-free-extras
gstreamer1-plugins-bad-freeworld
gstreamer1-plugins-good-extras
gstreamer1-plugins-good-gtk
gstreamer1-plugins-ugly
gstreamer1-plugins-ugly-free
gstreamer1-rtsp-server
gstreamer1-vaapi
hardinfo2
libavcodec-freeworld
mc
mpv
msvsphere-configs-gnome
msvsphere-nautilus-extensions
nautilus
openh264
rpmfusion-free-appstream-data
rpmfusion-free-release
rpmfusion-nonfree-appstream-data
rpmfusion-nonfree-release
sphere-desktop-selector
sphere-image-writer
telegram-desktop
tilix
vim

# google-chrome
google-chrome-stable

# onlyoffice
onlyoffice-desktopeditors

# obsolete packages
eog
evince
evince-djvu
evince-previewer
evince-thumbnailer
gedit
gedit-plugins

# Default editor
-nano-default-editor
vim-default-editor

# Video accel
libva-intel-hybrid-driver

%end
